import os


KEYWORDS = list(set([
    # Nuclear Energy
    "capacity factor",
    "unit capability factor",
    "safety system performance",
    "fuel performance",
    "small modular reactor",
    "microreactor",
    "advanced nuclear reactor",
    "fusion energy",
    "nuclear propulsion",
    "nuclear microgrid",
    "radioisotope thermoelectric generator",
    "high-assay low-enriched uranium",
    "thorium reactor",
    "nuclear thermal propulsion",
    "nuclear-enabled",
    "uranium enrichment",

    # Defense Tech
    "hypersonic",
    "hypersonics",
    "directed energy weapons",
    "quantum computing",
    "quantum science",
    "artificial intelligence",
    # "AI",
    "machine learning in defense",
    "autonomous defense systems",
    "unmanned systems",
    "defense logistics",
    "military cybersecurity",
    "electronic warfare",
    "zero trust security",
    "counter-drone",
    "stealth technology",
    "ISR (intelligence, surveillance, reconnaissance)",
    "defense supply chain",
    "additive manufacturing in defense",
    "dual-use technology",
    "space-based defense",
    "warfighter technology",

    # Space Industry
    "small satellite",
    "cubesat",
    "commercial spaceflight",
    "space propulsion",
    "lunar economy",
    "asteroid mining",
    "deep space exploration",
    "rapid prototyping",
    "critical technology",
    "biotechnology",
    "advanced materials",
    "5G in space",
    "orbital manufacturing",
    "low Earth orbit economy",
    "Mars mission",
    "lunar lander",
    "space station module",
    "Musk",
    "SpaceX",
    "Blue Origin",
    "Rocket Lab",
    "Sierra Space",
    "Relativity Space",
    "Astra",
    "Terran Orbital",
    "Firefly Aerospace",
    "Planet Labs"

    # COMPANIES

    # Space Industry
    "Rocket Lab",
    "Relativity Space",
    "Astra",
    "Firefly Aerospace",
    "Sierra Space",
    "Terran Orbital",
    "Planet Labs",
    "Impulse Space",
    "Redwire Space",
    "Blue Canyon Technologies",
    "AstroForge",
    "Orbit Fab",
    "The Exploration Company",
    "Vast Space",
    "Exotrail",
    "Sidus Space",
    "Momentus",
    "ABL Space Systems",
    "Vaya Space",
    "ISAR Aerospace",
    "Gilmour Space Technologies",

    # Nuclear Energy
    "NuScale Power",
    "X-energy",
    "Oklo",
    "Kairos Power",
    "TerraPower",
    "Ultra Safe Nuclear Corporation",
    "Radiant Nuclear",
    "Moltex Energy",
    "Elysium Industries",
    "ThorCon Power",
    "ARC Clean Energy",
    "BWXT Advanced Technologies",
    "Seaborg Technologies",
    "Last Energy",
    "Copenhagen Atomics",

    # Defense Tech
    "Shield AI",
    "Anduril Industries",
    "Kratos Defense & Security",
    "Epirus",
    "Palantir Technologies",
    "Hawkeye 360",
    "Vantage Robotics",
    "Echodyne",
    "Skydio",
    "Fortem Technologies",
    "Rebellion Defense",
    "Ghost Robotics",
    "Plymouth Rock Technologies",
    "Saronic",
    "Sarcos Technology and Robotics",
    "Dedrone",
    "D-Fend Solutions",
    "Darkhive",
    "Icarus Aerospace",
    "SpearUAV"

    # Maura
    "Record-breaking year",
    "New projects",
    "Increased investment",
    "Policy support",
    "SMR development",
    "Partnerships",
    "AI and data centers",
    "Capacity additions",
    "Tripling capacity",
    "Energy security",
    "Record funding",
    "Technology advancements",
    "Strategic acquisitions",
    "Modernization efforts",
    "Supply chain initiatives",
    "R&D expansion",
    "Emerging markets",
    "Workforce development",
    "Digital transformation",
    "Sustainability focus",
    "Decarbonization efforts",
    "Record-breaking revenue growth",
    "Positive cash flow",
    "Series B/C funding secured",
    "Low customer acquisition cost (CAC)",
    "High customer lifetime value (CLV)",
    "Expanding team/hiring spree",
    "Product-market fit achieved",
    "Low churn rate",
    "Healthy CLV to CAC ratio",
    "Extended runway",
    "High customer retention rate",
    "Positive net promoter score (NPS)",
    "Increasing monthly recurring revenue (MRR)",
    "Strategic partnerships formed",
    "New market expansion",
    "Operational deployment",
    "Successful testing",
    "Milestone achieved",
    "Rapid prototyping success",
    "Breakthrough innovation",
    "First-of-its-kind capability",
    "Strategic partnership formed",
    "Awarded next phase funding",
    "Combat-ready system delivered",
    "Enhanced situational awareness achieved",
    "Reduced development risks",
    "Record growth in market adoption",
    "Cyber-resilient system launched",
    "Export-ready technology approved",
    "Recognition at industry summits/events",
    "Record-breaking generation",
    "Increased capacity factor",
    "New reactor connections",
    "Successful testing",
    "Extended operations",
    "Zero fuel failures",
    "High unit capability factor (UCF)",
    "Low forced loss rate (FLR)",
    "Improved chemistry effectiveness",
    "Enhanced safety system performance",
    "Tripling capacity pledge",
    "New construction starts",
    "Operational excellence",
    "Innovation breakthroughs",
    "Regulatory approval",
    "100% year-over-year revenue growth",
    "Positive cash flow",
    "5:1 CLV to CAC ratio",
    "Below 5-7% annual churn rate",
    "80-90% gross margins",
    "10-15% month-over-month MRR growth",
    "20+ months cash runway",
    "High lead-to-customer velocity",
    "Increasing customer retention rate",
    "Rising DAU/MAU ratio",
    "Decreasing burn rate",
    "Expanding product-market fit"

    "Space Sales", "RTX", "Oceans XYZ", "Xona Space Systems", "New Orbit", "Scale Army",
    "Mori Associates", "Payload/Ignition", "Payload/Ignition", "Payload/Ignition", 
    "Payload/Ignition", "Laurie Diamond", "Nightwing", "Sierra Space", "Virgin Galactic", 
    "SpiderOak", "Payload/Ignition", "Moss Adams", "Payload/Ignition", "Sidereus Space", 
    "Payload/Ignition", "Payload/Ignition", "Payload/Ignition", "Stripe", "SIR", "Porsche Consulting", 
    "Payload/Ignition", "Payload/Ignition", "Payload/Ignition", "Copernic Space", "The Aerospace Corporation", 
    "Payload/Ignition", "SwissTwelve", "Payload/Ignition", "BlackSky", "Portal Systems", "Hogan Lovells", 
    "Astroscale", "Anduril", "Payload/Ignition", "Hub Exhibitions", "BlackSky", "Paperbak", 
    "Space Finance Corp", "Deloitte", "Astranis", "Prospectus", "Anduril", "Payload/Ignition", 
    "Payload/Ignition", "Digantara", "Seraphim", "Bank of America", "Albury Creative", "Latitude", 
    "Payload/Ignition", "Hermeus", "Moss Adams", "Sierra Space", "Little Candle Marketing", "Culture Crave", 
    "Deloitte", "Market Ascent", "UK Space Agency", "C-Ops", "Space Foundation", "Payload/Ignition", 
    "Lockheed Martin", "Unknown", "Unknown Company", "Unknown Company", "Skydweller Aero", 
    "Hudson Davis Communications", "Aerospace Corporation", "Payload/Ignition", "Vannevar Labs", 
    "Italian Trade Agency", "Hypergiant", "Payload/Ignition", "Payload/Ignition", "Shift5", "Saronic", 
    "Pearl Ventures", "Space Beach Law Lab", "Cisluna Industries", "SpaceWorks", "Sedaro Tech", 
    "Citizens Private Bank", "21Software", "Go-On Group", "Astro Mechanica", "Airbus US Space & Defense, Inc.", 
    "Neuco", "HEO Space", "Silicon Valley Bank (SVB Capital)", "Ultra Motion", "Hadrian", "Firestorm", 
    "Chaos Industries", "Axon Vision", "Epirus", "Spear", "Espre Technologies", "Cyber Forza", "Rebellion Defense", 
    "Scale AI", "Simplesense", "AeroVironment", "Shield AI", "Modern Intelligence AI", "Picogrid", 
    "Enabled Intelligence, Inc.", "TurbineOne", "Primer.AI", "Orbital Insight", "Capella Space", "Hawkeye 360", 
    "Umbra", "iDirect", "AGILESpaceIndustries", "manufacturo", "Modalic", "Deloitte", "Arkaea Media", 
    "Tectonic - Test", "NuScale Power", "Mile Earth", "NANO Nuclear Energy Inc.", "Kairos Power", 
    "TerraPower", "X Energy", "Oklo", "Seaborg Technologies", "Radiant Nuclear", "Aalo", "Type One Energy", 
    "Electric Fusion Systems, Inc.", "Boston Atomics", "Deutelio", "Curio LV", "Wyvern Space", "OpenC3", 
    "AstroTalent", "Greenberg Traurig Law", "ARX Robotics", "Lazarus AI", "Nominal", "CX2", "Improbable Defense", 
    "Avathon (F/K/A SparkCognition)", "Rhombus Power", "Advanced Navigation", "Terasynth", "Schemata", 
    "Obviant", "Mach9", "BMNT", "AnySignal", "MORSE Corp", "Striveworks", "Stratolaunch", "Numerica Corporation", 
    "Dispel", "Strategic Alliance Consulting, Inc. (Strategic ACI)", "SI2 Solutions", "EnerSys", "Qinetiq", 
    "Zen Technologies Limited", "Integrity Communications Solutions, Inc.", "Texas Nuclear Alliance", 
    "Paragon Energy Solutions", "Telespazio", "Leonardo", "Santee Cooper", "Constellation Energy - Ginna Nuclear Station", 
    "Wolverine Power Cooperative", "American Nuclear Society", "Mattermost", "Terrestrial Energy", "Pacific Fusion", 
    "Orano", "newcleo", "Last Energy", "Blue Energy", "Phoenix Neutron Imaging", "Transatomic Power", "Deep Fission", 
    "GOVRED", "Varonis", "Flock Safety", "DroneShield", "Oddball", "Emesent", "Yurts", "Dextral", "Fivecast", 
    "Virtru", "Axion Ray", "Asylon Robotics", "ZeroMark, Inc.", "Second Front", "Dragos", "Bastille", "Daedalus", 
    "Kongsberg Satellite Services", "Gama Space", "Slingshot Aerospace", "Satelles", "Varda Space Industries", 
    "World View", "Ghost Robotics", "goTenna", "Saildrone", "Bedrock", "JP Morgan", "Global Defense Insight", 
    "Argo Space", "Firehawk Aerospace", "Orbit Fab", "SubUAS LLC", "Bounce Imaging", "Echodyne", "Xplore", 
    "Wormhole", "American Astronautical Society", "New Frontier Aerospace", "Vantage Robotics", "ARIS Defense", 
    "Trabus Technologies", "Scout Space", "Vita Inclinata", "Jaia Robotics", "Skyryse", "WhiteFox Defense", 
    "M Aerospace RTC", "Aadi Space", "RAAD 360", "Combat Bound LLC", "Sesame Solar", "Air Refueling Tanker Transport", 
    "Above Space (Orbital Assembly Corporation)", "JetPack Aviation", "Airspace Defense, Inc.", "ARMR Systems", 
    "SICDRONE", "Inova Drone Inc.", "Valqari Drone Delivery", "Aerobotics7", "Circle Optics, Inc.", "Orbion", 
    "Target Arm Inc.", "Guardion Technologies, LLC", "ADAM Aerospace", "VerbaAI", "Nebula Cybersecurity", 
    "Crow Industries", "Airgility", "Paradigm Research and Engineering", "VastVision", "Element U.S. Space & Defense", 
    "SES Space & Defense", "APEX Space & Defense Systems", "ARQUIMEA", "Janicki", "Aevum Space and Defense", 
    "Laser Isotope Separation Technologies (LIS Technologies Inc.)", "Pillsbury Winthrop Shaw Pittman LLP", 
    "Haleu Energy Fuel", "ASP Isotopes", "Kiewit", "Baker Construction", "Pelican Energy Partners LP", "Hatch", 
    "Framatome North America", "Assystem", "Hydro One", "Centrus Energy", "GAINnuclear", "Ultra Safe Nuclear", 
    "Safire Partners", "Fusion and Fission Energy and Science Directorate", "Urenco USA", "Holtec International", 
    "Quanta Technology", "Focused Energy", "Tokamak Energy", "Curtiss-Wright Nuclear Division", "Entergy", 
    "Commonwealth Fusion Systems", "STEPtoFusion", "Thea Energy", "First Light Fusion", "NearStar Fusion", 
    "Helion", "FusionX Group", "Realta Fusion", "Promixa Fusion", "Gauss Fusion", "General Fusion", "Renaissance Fusion", 
    "Helical Fusion", "DIII-D National Fusion Facility", "Kyoto Fusioneering", "Moltex Energy", "Clean Core Thorium Energy", 
    "Hadron Energy", "The Thorium Network", "Lightbridge Corporation", "GTTSi", "Exodys Energy", 
    "Nuclear Energy Consultants, Inc.", "Nuclear Promise X", "Nuclear Electric Insurance Limited", "Southern Nuclear", 
    "Naval Nuclear Laboratory", "HII", "Keeper Security, Inc.", "Accenture Federal Services", "BE", "CYBER RANGES", 
    "Dassault Systèmes", "Diligent", "ECS", "Guidehouse", "HCLSoftware", "Janes", "Merlin Cyber", "StratasCorp Technologies", 
    "TekSynap", "CyLogic", "SD3IT", "OSI Federal Technologies, Inc.", "Dcode", "Maximus", "McKinsey & Company", 
    "Confluent", "SealingTech", "Systems Planning & Analysis", "Cloudera", "Fortinet Federal", "Owl Cyber Defense", 
    "Tyto Athene, LLC", "World Wide Technology", "BMC Software", "Everfox", "Belden", "Future Tech Enterprise, Inc.", 
    "Parraid, LLC", "Abaco Systems", "ADS, Inc.", "Ansys", "Apposite Technologies", "AltView Analytics", 
    "Elbit Systems of America", "Epiq Solutions", "Glenair, Inc", "Babel Street", "BlackBerry", "Cobham Satcom", 
    "GovEagle", "Hutchinson Aerospace and Industry", "Imenco", "Intellian Technologies", "INVISIO", "ITT Enidine", 
    "IXI Technology", "JT4", "TAE Technologies, Inc.", "Zap Energy", "Marvel Fusion", "Xcimer Energy Corporation", 
    "Chevron", "Eni", "Cenovus Energy Inc", "Space Foundation", "Deterrence", "Suhora", "JobsOhio, sourced by Fahlgren", 
    "Aalyria", "Albedo", "Amazon Web Services", "Apex", "Astranis", "Astrobotic", "Astrolab", "Astroscale", 
    "Astroscale Ltd", "ATLAS Space Operations", "AWS", "BAE Systems", "Ball Aerospace", "Barclays", "Benchmark Space Systems", 
    "BryceTech", "CASIS", "CesiumAstro", "Dhruva Space", "Epsilon3", "EVONA", "Exolaunch", "Exotrail", "First Resonance", 
    "Impulse Space", "Intelsat", "Intuitive Machines", "Invariant", "L3Harris", "L3harris", "Latitude", "Latitude", 
    "Linde", "Lunar Outpost", "Morpheus Space", "mp international inc", "NanoAvionics", "NGC", "Oliver Wyman", 
    "Orbit Fab", "Outpost Technologies Corporation", "PADT", "Phase Four", "Pixxel Space Technologies", "Planet", 
    "Redwire", "Relativity Space", "Safran Reosc", "Satellogic", "Sift", "SkyFi", "Slingshot Aerospace", 
    "Slingshot Aerospace", "Space Tango", "SpaceWERX", "Spire Global", "Starburst Aerospace", "Starfish Space", 
    "Stoke Space", "VAST", "Viasat", "Starfish Space"
    "Record-breaking year",
    "New projects",
    "Increased investment",
    "Policy support",
    "SMR development",
    "Partnerships",
    "AI and data centers",
    "AI",
    "Data centers",
    "Capacity additions",
    "Tripling capacity",
    "Energy security",
    "Record funding",
    "Technology advancements",
    "Strategic acquisitions",
    "Modernization efforts",
    "Supply chain initiatives",
    "R&D expansion",
    "Research and development expansion",
    "Emerging markets",
    "Workforce development",
    "Digital transformation",
    "Sustainability focus",
    "Decarbonization efforts",
    "Record-breaking revenue growth",
    "Positive cash flow",
    "Series B funding secured",
    "Series C funding secured",
    "Low customer acquisition cost",
    "CAC",
    "High customer lifetime value",
    "CLV",
    "Expanding team",
    "Hiring spree",
    "Product-market fit achieved",
    "Low churn rate",
    "Healthy CLV to CAC ratio",
    "Extended runway",
    "High customer retention rate",
    "Positive net promoter score",
    "NPS",
    "Increasing monthly recurring revenue",
    "MRR",
    "Strategic partnerships formed",
    "New market expansion",
    "Operational deployment",
    "Successful testing",
    "Milestone achieved",
    "Rapid prototyping success",
    "Breakthrough innovation",
    "First-of-its-kind capability",
    "Strategic partnership formed",
    "Awarded next phase funding",
    "Combat-ready system delivered",
    "Enhanced situational awareness achieved",
    "Reduced development risks",
    "Record growth in market adoption",
    "Cyber-resilient system launched",
    "Export-ready technology approved",
    "Recognition at industry summits",
    "Recognition at industry events",
    "Record-breaking generation",
    "Increased capacity factor",
    "New reactor connections",
    "Successful testing",
    "Extended operations",
    "Zero fuel failures",
    "High unit capability factor",
    "UCF",
    "Low forced loss rate",
    "FLR",
    "Improved chemistry effectiveness",
    "Enhanced safety system performance",
    "Tripling capacity pledge",
    "New construction starts",
    "Operational excellence",
    "Innovation breakthroughs",
    "Regulatory approval",
    "100% year-over-year revenue growth",
    "Positive cash flow",
    "5:1 CLV to CAC ratio",
    "Below 5-7% annual churn rate",
    "80-90% gross margins",
    "10-15% month-over-month MRR growth",
    "20+ months cash runway",
    "High lead-to-customer velocity",
    "Increasing customer retention rate",
    "Rising DAU to MAU ratio",
    "DAU",
    "MAU",
    "Decreasing burn rate",
    "Expanding product-market fit",
]))




RSS_FEEDS = [
    # Nuclear Energy
    "https://world-nuclear-news.org/RSS",
    "https://feeds.feedburner.com/EERECleanCitiesNews",
    "https://www.iaea.org/newscenter/news/rss",
    "https://www.neimagazine.com/rss/news/",
    "https://www.nuclearnewswire.com/feed/",
    "https://www.nuclearpowerdaily.com/rss/",
    "https://www.nrc.gov/reading-rm/doc-collections/news/rss.xml",
    "https://www.ans.org/news/feed/",

    # Defense Technology
    "https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml", 
    "https://breakingdefense.com/feed/",
    "https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?max=10&ContentType=1&Site=945",
    "https://www.defenseworld.net/rss/",
    "https://www.army-technology.com/feed/",
    "https://www.naval-technology.com/feed/",
    "https://www.airforce-technology.com/feed/",
    "https://www.defenseindustrydaily.com/feed/",
    
    # Space Industry
    "https://www.nasa.gov/rss/dyn/breaking_news.rss",
    "https://spacenews.com/feed/",
    "https://www.space.com/feeds/all",
    "https://arstechnica.com/category/space/feed/",
    "https://spacepolicyonline.com/feed/",
    "https://www.thespacereview.com/articles.xml",
    "https://spaceref.com/rss",
    "https://www.orbitaltoday.com/feed/",
    "https://spacewatch.global/feed/",
    "https://spaceq.ca/feed/",
    "https://www.spacepolicyonline.com/feed/",
    "https://www.spaceintelreport.com/feed/",
    "https://spacewatch.global/feed/",
    "https://www.spacebridge.com/feed/",
]


# Database configuration (using a local SQLite file)
BASE_DIR = os.path.abspath(os.path.dirname(__file__))
DATABASE_URI = "sqlite:///" + os.path.join(BASE_DIR, "articles.db")

# Only consider articles from the past X days (e.g., 30 days)
DAYS_LIMIT = 30

# Scheduler or scraping time (placeholder):
SCRAPE_TIME = "12:00"  # Daily at 12:00 local time (could be used with cron or APScheduler)
